name = "chillbroz005-portfolio"
pages_build_output_dir = "./out"
compatibility_date = "2026-09-28"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-auth"
database_id = "06e3e0c0-07ab-404a-8fbe-6e5938c6c623"

[limits]
cpu_ms = 30000
